// Auto-generated image asset map for vothienhien.com
// Generated: 2026-04-20T09:32:32.847Z
// Usage: import { IMAGES } from "@/lib/images";
//        <Image src={IMAGES.heroPortrait.cdn} alt={IMAGES.heroPortrait.alt} />

export const IMAGES = {
  heroPortrait: {
    id: "hero-portrait",
    name: "Homepage Hero Portrait",
    category: "hero",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/hero-portrait-8ed7de4d.webp",
    local: "/images/hero/hero-portrait.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/hero-portrait-8ed7de4d.webp",
    alt: "Homepage Hero Portrait - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  profileHero: {
    id: "profile-hero",
    name: "Profile Page Hero - Desk Portrait",
    category: "hero",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/profile-hero-6c5a93e0.webp",
    local: "/images/hero/profile-hero.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/profile-hero-6c5a93e0.webp",
    alt: "Profile Page Hero - Desk Portrait - vothienhien.com",
    width: 1600,
    aspect: "16:9",
  },
  detailHands: {
    id: "detail-hands",
    name: "Detail Accent Shot - Hands with Pen",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/detail-hands-34b089bb.webp",
    local: "/images/content/detail-hands.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/detail-hands-34b089bb.webp",
    alt: "Detail Accent Shot - Hands with Pen - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceCivil: {
    id: "practice-civil",
    name: "Practice Area - Civil Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-civil-9e32fb02.webp",
    local: "/images/content/practice-civil.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-civil-9e32fb02.webp",
    alt: "Practice Area - Civil Disputes - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceLand: {
    id: "practice-land",
    name: "Practice Area - Land & Real Estate",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-land-bbc1cc7f.webp",
    local: "/images/content/practice-land.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-land-bbc1cc7f.webp",
    alt: "Practice Area - Land & Real Estate - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceFamily: {
    id: "practice-family",
    name: "Practice Area - Family Law & Divorce",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-family-c50dd275.webp",
    local: "/images/content/practice-family.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-family-c50dd275.webp",
    alt: "Practice Area - Family Law & Divorce - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceCorporate: {
    id: "practice-corporate",
    name: "Practice Area - Corporate Law",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-corporate-5f2c5501.webp",
    local: "/images/content/practice-corporate.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-corporate-5f2c5501.webp",
    alt: "Practice Area - Corporate Law - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceLabor: {
    id: "practice-labor",
    name: "Practice Area - Labor Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-labor-aec105be.webp",
    local: "/images/content/practice-labor.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-labor-aec105be.webp",
    alt: "Practice Area - Labor Disputes - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceCriminal: {
    id: "practice-criminal",
    name: "Practice Area - Criminal Defense",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-criminal-59f8f545.webp",
    local: "/images/content/practice-criminal.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-criminal-59f8f545.webp",
    alt: "Practice Area - Criminal Defense - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  bgLibrary: {
    id: "bg-library",
    name: "Library / Publications Background",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-library-f8675605.webp",
    local: "/images/background/bg-library.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-library-f8675605.webp",
    alt: "Library / Publications Background - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  bgSkyline: {
    id: "bg-skyline",
    name: "HCMC Skyline Panoramic",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-skyline-4d8d3819.webp",
    local: "/images/background/bg-skyline.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-skyline-4d8d3819.webp",
    alt: "HCMC Skyline Panoramic - vothienhien.com",
    width: 1920,
    aspect: "21:9",
  },
  accentGoldStroke: {
    id: "accent-gold-stroke",
    name: "Gold Brushstroke Decorative Element",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/accent-gold-stroke-4de2a341.webp",
    local: "/images/content/accent-gold-stroke.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/accent-gold-stroke-4de2a341.webp",
    alt: "Gold Brushstroke Decorative Element - vothienhien.com",
    width: 800,
    aspect: "16:9",
  },
  bgMarble: {
    id: "bg-marble",
    name: "Dark Marble Texture Background",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-marble-5a92903f.webp",
    local: "/images/background/bg-marble.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-marble-5a92903f.webp",
    alt: "Dark Marble Texture Background - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  bgSpeaking: {
    id: "bg-speaking",
    name: "Conference / Speaking Event",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/bg-speaking-d2c1c550.webp",
    local: "/images/content/bg-speaking.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/bg-speaking-d2c1c550.webp",
    alt: "Conference / Speaking Event - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  bgDistrict1: {
    id: "bg-district1",
    name: "District 1 HCMC Aerial",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-district1-83512275.webp",
    local: "/images/background/bg-district1.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-district1-83512275.webp",
    alt: "District 1 HCMC Aerial - vothienhien.com",
    width: 1600,
    aspect: "16:9",
  },
  ogDefault: {
    id: "og-default",
    name: "Default OG / Social Sharing Image",
    category: "og",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-default-a229973b.webp",
    local: "/images/og/og-default.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-default-a229973b.webp",
    alt: "Default OG / Social Sharing Image - vothienhien.com",
    width: 1200,
    aspect: "1200:630",
  },
  ogPractice: {
    id: "og-practice",
    name: "Practice Areas OG Image",
    category: "og",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-practice-f106e559.webp",
    local: "/images/og/og-practice.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-practice-f106e559.webp",
    alt: "Practice Areas OG Image - vothienhien.com",
    width: 1200,
    aspect: "1200:630",
  },
  faviconVh: {
    id: "favicon-vh",
    name: "VH Monogram Favicon/App Icon",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/favicon-vh-8cdbcafc.webp",
    local: "/images/icon/favicon-vh.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/favicon-vh-8cdbcafc.webp",
    alt: "VH Monogram Favicon/App Icon - vothienhien.com",
    width: 512,
    aspect: "1:1",
  },
  articleCorporateLaw: {
    id: "article-corporate-law",
    name: "Article Thumbnail - Corporate Law Analysis",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-corporate-law-cd404779.webp",
    local: "/images/content/article-corporate-law.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-corporate-law-cd404779.webp",
    alt: "Article Thumbnail - Corporate Law Analysis - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLandDispute: {
    id: "article-land-dispute",
    name: "Article Thumbnail - Land & Property Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-land-dispute-28b8d87f.webp",
    local: "/images/content/article-land-dispute.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-land-dispute-28b8d87f.webp",
    alt: "Article Thumbnail - Land & Property Disputes - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleForeignInvestment: {
    id: "article-foreign-investment",
    name: "Article Thumbnail - Foreign Investment in Vietnam",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-foreign-investment-087a2566.webp",
    local: "/images/content/article-foreign-investment.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-foreign-investment-087a2566.webp",
    alt: "Article Thumbnail - Foreign Investment in Vietnam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleDivorceInternational: {
    id: "article-divorce-international",
    name: "Article Thumbnail - International Divorce",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-divorce-international-66f796f8.webp",
    local: "/images/content/article-divorce-international.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-divorce-international-66f796f8.webp",
    alt: "Article Thumbnail - International Divorce - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLaborRights: {
    id: "article-labor-rights",
    name: "Article Thumbnail - Labor Rights & Employment",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-labor-rights-f201efee.webp",
    local: "/images/content/article-labor-rights.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-labor-rights-f201efee.webp",
    alt: "Article Thumbnail - Labor Rights & Employment - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleCriminalDefense: {
    id: "article-criminal-defense",
    name: "Article Thumbnail - Criminal Defense & Rights",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-criminal-defense-3fb4bf85.webp",
    local: "/images/content/article-criminal-defense.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-criminal-defense-3fb4bf85.webp",
    alt: "Article Thumbnail - Criminal Defense & Rights - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionConsultation: {
    id: "section-consultation",
    name: "Consultation Room - Practice Area Pages",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-consultation-09ce3923.webp",
    local: "/images/content/section-consultation.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-consultation-09ce3923.webp",
    alt: "Consultation Room - Practice Area Pages - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionCourtroom: {
    id: "section-courtroom",
    name: "Vietnamese Courtroom Interior",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-courtroom-e20bbb8d.webp",
    local: "/images/content/section-courtroom.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-courtroom-e20bbb8d.webp",
    alt: "Vietnamese Courtroom Interior - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionDocumentSigning: {
    id: "section-document-signing",
    name: "Legal Document Signing Close-up",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-document-signing-63dc5758.webp",
    local: "/images/content/section-document-signing.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-document-signing-63dc5758.webp",
    alt: "Legal Document Signing Close-up - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  sectionClientMeeting: {
    id: "section-client-meeting",
    name: "Attorney-Client Meeting",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-client-meeting-e1f7235e.webp",
    local: "/images/content/section-client-meeting.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-client-meeting-e1f7235e.webp",
    alt: "Attorney-Client Meeting - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionTeamDiscussion: {
    id: "section-team-discussion",
    name: "Legal Team Discussion",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-team-discussion-8b1a2a78.webp",
    local: "/images/content/section-team-discussion.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-team-discussion-8b1a2a78.webp",
    alt: "Legal Team Discussion - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  perspectiveThought: {
    id: "perspective-thought",
    name: "Thoughtful Lawyer Portrait - Perspectives",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/perspective-thought-740b9752.webp",
    local: "/images/content/perspective-thought.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/perspective-thought-740b9752.webp",
    alt: "Thoughtful Lawyer Portrait - Perspectives - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  bgLegalBooks: {
    id: "bg-legal-books",
    name: "Legal Books Close-up Background",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-legal-books-abdaa863.webp",
    local: "/images/background/bg-legal-books.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-legal-books-abdaa863.webp",
    alt: "Legal Books Close-up Background - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  bgOfficeHallway: {
    id: "bg-office-hallway",
    name: "Law Office Hallway - Premium Interior",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-office-hallway-e2bffaa5.webp",
    local: "/images/background/bg-office-hallway.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-office-hallway-e2bffaa5.webp",
    alt: "Law Office Hallway - Premium Interior - vothienhien.com",
    width: 1920,
    aspect: "21:9",
  },
  iconScalesGold: {
    id: "icon-scales-gold",
    name: "Gold Scales of Justice Icon",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/icon-scales-gold-b8487acf.webp",
    local: "/images/icon/icon-scales-gold.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/icon-scales-gold-b8487acf.webp",
    alt: "Gold Scales of Justice Icon - vothienhien.com",
    width: 512,
    aspect: "1:1",
  },
  mapHcmcOffice: {
    id: "map-hcmc-office",
    name: "Stylized HCMC Office Location Map",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/map-hcmc-office-58683e9b.webp",
    local: "/images/content/map-hcmc-office.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/map-hcmc-office-58683e9b.webp",
    alt: "Stylized HCMC Office Location Map - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  practiceCommercial: {
    id: "practice-commercial",
    name: "Practice Area - Commercial Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-commercial-b5a1a6d9.webp",
    local: "/images/content/practice-commercial.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-commercial-b5a1a6d9.webp",
    alt: "Practice Area - Commercial Disputes - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  articleCommercialArbitration: {
    id: "article-commercial-arbitration",
    name: "Article Thumbnail - Commercial Arbitration at VIAC",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-arbitration-d880f072.webp",
    local: "/images/content/article-commercial-arbitration.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-arbitration-d880f072.webp",
    alt: "Article Thumbnail - Commercial Arbitration at VIAC - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleCommercialLitigation: {
    id: "article-commercial-litigation",
    name: "Article Thumbnail - Commercial Court Litigation",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-litigation-5b2e9165.webp",
    local: "/images/content/article-commercial-litigation.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-litigation-5b2e9165.webp",
    alt: "Article Thumbnail - Commercial Court Litigation - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionArbitrationHearing: {
    id: "section-arbitration-hearing",
    name: "Arbitration Hearing in Progress",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-arbitration-hearing-16452da6.webp",
    local: "/images/content/section-arbitration-hearing.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-arbitration-hearing-16452da6.webp",
    alt: "Arbitration Hearing in Progress - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  bgCommercialSkyline: {
    id: "bg-commercial-skyline",
    name: "HCMC Financial District - Commercial Context",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-commercial-skyline-b4d48c2b.webp",
    local: "/images/background/bg-commercial-skyline.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-commercial-skyline-b4d48c2b.webp",
    alt: "HCMC Financial District - Commercial Context - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  ogCommercial: {
    id: "og-commercial",
    name: "Commercial Disputes OG Image",
    category: "og",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-commercial-2c393856.webp",
    local: "/images/og/og-commercial.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-commercial-2c393856.webp",
    alt: "Commercial Disputes OG Image - vothienhien.com",
    width: 1200,
    aspect: "1200:630",
  },
  logoSymbolic1Scales: {
    id: "logo-symbolic-1-scales",
    name: "Logo Variation 1 — Bold Scales of Justice",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-1-scales-e3a0ad3c.webp",
    local: "/images/icon/logo-symbolic-1-scales.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-1-scales-e3a0ad3c.webp",
    alt: "Logo Variation 1 — Bold Scales of Justice - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  },
  logoSymbolic2Pillar: {
    id: "logo-symbolic-2-pillar",
    name: "Logo Variation 2 — Classical Pillar of Law",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-2-pillar-591535f2.webp",
    local: "/images/icon/logo-symbolic-2-pillar.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-2-pillar-591535f2.webp",
    alt: "Logo Variation 2 — Classical Pillar of Law - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  },
  logoSymbolic3GavelBook: {
    id: "logo-symbolic-3-gavel-book",
    name: "Logo Variation 3 — Gavel and Open Book Crest",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-3-gavel-book-dd31767a.webp",
    local: "/images/icon/logo-symbolic-3-gavel-book.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-3-gavel-book-dd31767a.webp",
    alt: "Logo Variation 3 — Gavel and Open Book Crest - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  },
  logoSymbolic4LaurelScales: {
    id: "logo-symbolic-4-laurel-scales",
    name: "Logo Variation 4 — Laurel Wreath Around Scales",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-4-laurel-scales-9484800b.webp",
    local: "/images/icon/logo-symbolic-4-laurel-scales.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-4-laurel-scales-9484800b.webp",
    alt: "Logo Variation 4 — Laurel Wreath Around Scales - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  }
} as const;

export type ImageId = keyof typeof IMAGES;
