// Auto-generated image asset map for vothienhien.com
// Generated: 2026-05-18T19:08:50.686Z
// Usage: import { IMAGES } from "@/lib/images";
//        <Image src={IMAGES.heroPortrait.cdn} alt={IMAGES.heroPortrait.alt} />

export const IMAGES = {
  heroPortrait: {
    id: "hero-portrait",
    name: "Homepage Hero Portrait",
    category: "hero",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/hero-portrait-8ed7de4d.webp",
    local: "/images/hero/hero-portrait.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/hero-portrait-8ed7de4d.webp",
    alt: "Homepage Hero Portrait - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  profileHero: {
    id: "profile-hero",
    name: "Profile Page Hero - Desk Portrait",
    category: "hero",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/profile-hero-6c5a93e0.webp",
    local: "/images/hero/profile-hero.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/hero/profile-hero-6c5a93e0.webp",
    alt: "Profile Page Hero - Desk Portrait - vothienhien.com",
    width: 1600,
    aspect: "16:9",
  },
  detailHands: {
    id: "detail-hands",
    name: "Detail Accent Shot - Hands with Pen",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/detail-hands-34b089bb.webp",
    local: "/images/content/detail-hands.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/detail-hands-34b089bb.webp",
    alt: "Detail Accent Shot - Hands with Pen - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceCivil: {
    id: "practice-civil",
    name: "Practice Area - Civil Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-civil-9e32fb02.webp",
    local: "/images/content/practice-civil.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-civil-9e32fb02.webp",
    alt: "Practice Area - Civil Disputes - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceLand: {
    id: "practice-land",
    name: "Practice Area - Land & Real Estate",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-land-bbc1cc7f.webp",
    local: "/images/content/practice-land.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-land-bbc1cc7f.webp",
    alt: "Practice Area - Land & Real Estate - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceFamily: {
    id: "practice-family",
    name: "Practice Area - Family Law & Divorce",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-family-c50dd275.webp",
    local: "/images/content/practice-family.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-family-c50dd275.webp",
    alt: "Practice Area - Family Law & Divorce - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceCorporate: {
    id: "practice-corporate",
    name: "Practice Area - Corporate Law",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-corporate-5f2c5501.webp",
    local: "/images/content/practice-corporate.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-corporate-5f2c5501.webp",
    alt: "Practice Area - Corporate Law - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceLabor: {
    id: "practice-labor",
    name: "Practice Area - Labor Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-labor-aec105be.webp",
    local: "/images/content/practice-labor.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-labor-aec105be.webp",
    alt: "Practice Area - Labor Disputes - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  practiceCriminal: {
    id: "practice-criminal",
    name: "Practice Area - Criminal Defense",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-criminal-59f8f545.webp",
    local: "/images/content/practice-criminal.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-criminal-59f8f545.webp",
    alt: "Practice Area - Criminal Defense - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  bgLibrary: {
    id: "bg-library",
    name: "Library / Publications Background",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-library-f8675605.webp",
    local: "/images/background/bg-library.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-library-f8675605.webp",
    alt: "Library / Publications Background - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  bgSkyline: {
    id: "bg-skyline",
    name: "HCMC Skyline Panoramic",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-skyline-4d8d3819.webp",
    local: "/images/background/bg-skyline.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-skyline-4d8d3819.webp",
    alt: "HCMC Skyline Panoramic - vothienhien.com",
    width: 1920,
    aspect: "21:9",
  },
  accentGoldStroke: {
    id: "accent-gold-stroke",
    name: "Gold Brushstroke Decorative Element",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/accent-gold-stroke-4de2a341.webp",
    local: "/images/content/accent-gold-stroke.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/accent-gold-stroke-4de2a341.webp",
    alt: "Gold Brushstroke Decorative Element - vothienhien.com",
    width: 800,
    aspect: "16:9",
  },
  bgMarble: {
    id: "bg-marble",
    name: "Dark Marble Texture Background",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-marble-5a92903f.webp",
    local: "/images/background/bg-marble.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-marble-5a92903f.webp",
    alt: "Dark Marble Texture Background - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  bgSpeaking: {
    id: "bg-speaking",
    name: "Conference / Speaking Event",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/bg-speaking-d2c1c550.webp",
    local: "/images/content/bg-speaking.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/bg-speaking-d2c1c550.webp",
    alt: "Conference / Speaking Event - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  bgDistrict1: {
    id: "bg-district1",
    name: "District 1 HCMC Aerial",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-district1-83512275.webp",
    local: "/images/background/bg-district1.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-district1-83512275.webp",
    alt: "District 1 HCMC Aerial - vothienhien.com",
    width: 1600,
    aspect: "16:9",
  },
  ogDefault: {
    id: "og-default",
    name: "Default OG / Social Sharing Image",
    category: "og",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-default-a229973b.webp",
    local: "/images/og/og-default.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-default-a229973b.webp",
    alt: "Default OG / Social Sharing Image - vothienhien.com",
    width: 1200,
    aspect: "1200:630",
  },
  ogPractice: {
    id: "og-practice",
    name: "Practice Areas OG Image",
    category: "og",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-practice-f106e559.webp",
    local: "/images/og/og-practice.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-practice-f106e559.webp",
    alt: "Practice Areas OG Image - vothienhien.com",
    width: 1200,
    aspect: "1200:630",
  },
  faviconVh: {
    id: "favicon-vh",
    name: "VH Monogram Favicon/App Icon",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/favicon-vh-8cdbcafc.webp",
    local: "/images/icon/favicon-vh.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/favicon-vh-8cdbcafc.webp",
    alt: "VH Monogram Favicon/App Icon - vothienhien.com",
    width: 512,
    aspect: "1:1",
  },
  articleCorporateLaw: {
    id: "article-corporate-law",
    name: "Article Thumbnail - Corporate Law Analysis",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-corporate-law-cd404779.webp",
    local: "/images/content/article-corporate-law.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-corporate-law-cd404779.webp",
    alt: "Article Thumbnail - Corporate Law Analysis - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLandDispute: {
    id: "article-land-dispute",
    name: "Article Thumbnail - Land & Property Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-land-dispute-28b8d87f.webp",
    local: "/images/content/article-land-dispute.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-land-dispute-28b8d87f.webp",
    alt: "Article Thumbnail - Land & Property Disputes - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleForeignInvestment: {
    id: "article-foreign-investment",
    name: "Article Thumbnail - Foreign Investment in Vietnam",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-foreign-investment-087a2566.webp",
    local: "/images/content/article-foreign-investment.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-foreign-investment-087a2566.webp",
    alt: "Article Thumbnail - Foreign Investment in Vietnam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleDivorceInternational: {
    id: "article-divorce-international",
    name: "Article Thumbnail - International Divorce",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-divorce-international-66f796f8.webp",
    local: "/images/content/article-divorce-international.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-divorce-international-66f796f8.webp",
    alt: "Article Thumbnail - International Divorce - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLaborRights: {
    id: "article-labor-rights",
    name: "Article Thumbnail - Labor Rights & Employment",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-labor-rights-f201efee.webp",
    local: "/images/content/article-labor-rights.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-labor-rights-f201efee.webp",
    alt: "Article Thumbnail - Labor Rights & Employment - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleCriminalDefense: {
    id: "article-criminal-defense",
    name: "Article Thumbnail - Criminal Defense & Rights",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-criminal-defense-3fb4bf85.webp",
    local: "/images/content/article-criminal-defense.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-criminal-defense-3fb4bf85.webp",
    alt: "Article Thumbnail - Criminal Defense & Rights - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionConsultation: {
    id: "section-consultation",
    name: "Consultation Room - Practice Area Pages",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-consultation-09ce3923.webp",
    local: "/images/content/section-consultation.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-consultation-09ce3923.webp",
    alt: "Consultation Room - Practice Area Pages - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionCourtroom: {
    id: "section-courtroom",
    name: "Vietnamese Courtroom Interior",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-courtroom-e20bbb8d.webp",
    local: "/images/content/section-courtroom.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-courtroom-e20bbb8d.webp",
    alt: "Vietnamese Courtroom Interior - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionDocumentSigning: {
    id: "section-document-signing",
    name: "Legal Document Signing Close-up",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-document-signing-63dc5758.webp",
    local: "/images/content/section-document-signing.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-document-signing-63dc5758.webp",
    alt: "Legal Document Signing Close-up - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  sectionClientMeeting: {
    id: "section-client-meeting",
    name: "Attorney-Client Meeting",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-client-meeting-e1f7235e.webp",
    local: "/images/content/section-client-meeting.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-client-meeting-e1f7235e.webp",
    alt: "Attorney-Client Meeting - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionTeamDiscussion: {
    id: "section-team-discussion",
    name: "Legal Team Discussion",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-team-discussion-8b1a2a78.webp",
    local: "/images/content/section-team-discussion.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-team-discussion-8b1a2a78.webp",
    alt: "Legal Team Discussion - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  perspectiveThought: {
    id: "perspective-thought",
    name: "Thoughtful Lawyer Portrait - Perspectives",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/perspective-thought-740b9752.webp",
    local: "/images/content/perspective-thought.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/perspective-thought-740b9752.webp",
    alt: "Thoughtful Lawyer Portrait - Perspectives - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  bgLegalBooks: {
    id: "bg-legal-books",
    name: "Legal Books Close-up Background",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-legal-books-abdaa863.webp",
    local: "/images/background/bg-legal-books.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-legal-books-abdaa863.webp",
    alt: "Legal Books Close-up Background - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  bgOfficeHallway: {
    id: "bg-office-hallway",
    name: "Law Office Hallway - Premium Interior",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-office-hallway-e2bffaa5.webp",
    local: "/images/background/bg-office-hallway.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-office-hallway-e2bffaa5.webp",
    alt: "Law Office Hallway - Premium Interior - vothienhien.com",
    width: 1920,
    aspect: "21:9",
  },
  iconScalesGold: {
    id: "icon-scales-gold",
    name: "Gold Scales of Justice Icon",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/icon-scales-gold-b8487acf.webp",
    local: "/images/icon/icon-scales-gold.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/icon-scales-gold-b8487acf.webp",
    alt: "Gold Scales of Justice Icon - vothienhien.com",
    width: 512,
    aspect: "1:1",
  },
  mapHcmcOffice: {
    id: "map-hcmc-office",
    name: "Stylized HCMC Office Location Map",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/map-hcmc-office-58683e9b.webp",
    local: "/images/content/map-hcmc-office.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/map-hcmc-office-58683e9b.webp",
    alt: "Stylized HCMC Office Location Map - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  practiceCommercial: {
    id: "practice-commercial",
    name: "Practice Area - Commercial Disputes",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-commercial-b5a1a6d9.webp",
    local: "/images/content/practice-commercial.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/practice-commercial-b5a1a6d9.webp",
    alt: "Practice Area - Commercial Disputes - vothienhien.com",
    width: 1200,
    aspect: "3:2",
  },
  articleCommercialArbitration: {
    id: "article-commercial-arbitration",
    name: "Article Thumbnail - Commercial Arbitration at VIAC",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-arbitration-d880f072.webp",
    local: "/images/content/article-commercial-arbitration.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-arbitration-d880f072.webp",
    alt: "Article Thumbnail - Commercial Arbitration at VIAC - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleCommercialLitigation: {
    id: "article-commercial-litigation",
    name: "Article Thumbnail - Commercial Court Litigation",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-litigation-5b2e9165.webp",
    local: "/images/content/article-commercial-litigation.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/article-commercial-litigation-5b2e9165.webp",
    alt: "Article Thumbnail - Commercial Court Litigation - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  sectionArbitrationHearing: {
    id: "section-arbitration-hearing",
    name: "Arbitration Hearing in Progress",
    category: "content",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-arbitration-hearing-16452da6.webp",
    local: "/images/content/section-arbitration-hearing.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/content/section-arbitration-hearing-16452da6.webp",
    alt: "Arbitration Hearing in Progress - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  bgCommercialSkyline: {
    id: "bg-commercial-skyline",
    name: "HCMC Financial District - Commercial Context",
    category: "background",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-commercial-skyline-b4d48c2b.webp",
    local: "/images/background/bg-commercial-skyline.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/background/bg-commercial-skyline-b4d48c2b.webp",
    alt: "HCMC Financial District - Commercial Context - vothienhien.com",
    width: 1920,
    aspect: "16:9",
  },
  ogCommercial: {
    id: "og-commercial",
    name: "Commercial Disputes OG Image",
    category: "og",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-commercial-2c393856.webp",
    local: "/images/og/og-commercial.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/og/og-commercial-2c393856.webp",
    alt: "Commercial Disputes OG Image - vothienhien.com",
    width: 1200,
    aspect: "1200:630",
  },
  logoSymbolic1Scales: {
    id: "logo-symbolic-1-scales",
    name: "Logo Variation 1 — Bold Scales of Justice",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-1-scales-e3a0ad3c.webp",
    local: "/images/icon/logo-mark-1-scales.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-1-scales-e3a0ad3c.webp",
    alt: "Logo Variation 1 — Bold Scales of Justice - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  },
  logoSymbolic2Pillar: {
    id: "logo-symbolic-2-pillar",
    name: "Logo Variation 2 — Classical Pillar of Law",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-2-pillar-591535f2.webp",
    local: "/images/icon/logo-mark-2-pillar.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-2-pillar-591535f2.webp",
    alt: "Logo Variation 2 — Classical Pillar of Law - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  },
  logoSymbolic3GavelBook: {
    id: "logo-symbolic-3-gavel-book",
    name: "Logo Variation 3 — Gavel and Open Book Crest",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-3-gavel-book-dd31767a.webp",
    local: "/images/icon/logo-mark-3-gavel-book.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-3-gavel-book-dd31767a.webp",
    alt: "Logo Variation 3 — Gavel and Open Book Crest - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  },
  logoSymbolic4LaurelScales: {
    id: "logo-symbolic-4-laurel-scales",
    name: "Logo Variation 4 — Laurel Wreath Around Scales",
    category: "icon",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-4-laurel-scales-9484800b.webp",
    local: "/images/icon/logo-mark-4-laurel-scales.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/icon/logo-symbolic-4-laurel-scales-9484800b.webp",
    alt: "Logo Variation 4 — Laurel Wreath Around Scales - vothienhien.com",
    width: 1024,
    aspect: "1:1",
  },
  articleWorkPermitRequirementsVietnamCompleteGuide: {
    id: "article-work-permit-requirements-vietnam-complete-guide",
    name: "Work Permit Requirements in Vietnam: Complete Guide for E…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-work-permit-requirements-vietnam-complete-guide-9d5cb244.webp",
    local: "/images/blog/article-work-permit-requirements-vietnam-complete-guide.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-work-permit-requirements-vietnam-complete-guide-9d5cb244.webp",
    alt: "Work Permit Requirements in Vietnam: Complete Guide for E… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleBankingFinanceRegulationsVietnamForeignInvestors: {
    id: "article-banking-finance-regulations-vietnam-foreign-investors",
    name: "Banking and Finance Regulations in Vietnam: Guide for For…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-banking-finance-regulations-vietnam-foreign-investors-10cf1a48.webp",
    local: "/images/blog/article-banking-finance-regulations-vietnam-foreign-investors.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-banking-finance-regulations-vietnam-foreign-investors-10cf1a48.webp",
    alt: "Banking and Finance Regulations in Vietnam: Guide for For… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleEnvironmentalLawComplianceVietnamIndustrialProjects: {
    id: "article-environmental-law-compliance-vietnam-industrial-projects",
    name: "Environmental Law Compliance in Vietnam: Requirements for…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-environmental-law-compliance-vietnam-industrial-projects-2ec5e72c.webp",
    local: "/images/blog/article-environmental-law-compliance-vietnam-industrial-projects.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-environmental-law-compliance-vietnam-industrial-projects-2ec5e72c.webp",
    alt: "Environmental Law Compliance in Vietnam: Requirements for… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleVietnamECommerceRegulationsLegalCompliance: {
    id: "article-vietnam-e-commerce-regulations-legal-compliance",
    name: "Vietnam E-Commerce Regulations: Legal Compliance for Onli…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-e-commerce-regulations-legal-compliance-b520df6a.webp",
    local: "/images/blog/article-vietnam-e-commerce-regulations-legal-compliance.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-e-commerce-regulations-legal-compliance-b520df6a.webp",
    alt: "Vietnam E-Commerce Regulations: Legal Compliance for Onli… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleJointVenturesVietnamLegalStructureGovernanceExit: {
    id: "article-joint-ventures-vietnam-legal-structure-governance-exit",
    name: "Joint Ventures in Vietnam: Legal Structure, Governance, a…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-joint-ventures-vietnam-legal-structure-governance-exit-cb3cec44.webp",
    local: "/images/blog/article-joint-ventures-vietnam-legal-structure-governance-exit.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-joint-ventures-vietnam-legal-structure-governance-exit-cb3cec44.webp",
    alt: "Joint Ventures in Vietnam: Legal Structure, Governance, a… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleInheritanceLawVietnamRightsForeignHeirs: {
    id: "article-inheritance-law-vietnam-rights-foreign-heirs",
    name: "Inheritance Law in Vietnam: Rights of Foreign Heirs",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-inheritance-law-vietnam-rights-foreign-heirs-944624cf.webp",
    local: "/images/blog/article-inheritance-law-vietnam-rights-foreign-heirs.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-inheritance-law-vietnam-rights-foreign-heirs-944624cf.webp",
    alt: "Inheritance Law in Vietnam: Rights of Foreign Heirs - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleDataPrivacyLawVietnamPdpdComplianceGuide: {
    id: "article-data-privacy-law-vietnam-pdpd-compliance-guide",
    name: "Data Privacy Law in Vietnam: PDPD Compliance Guide for Bu…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-data-privacy-law-vietnam-pdpd-compliance-guide-76a24d43.webp",
    local: "/images/blog/article-data-privacy-law-vietnam-pdpd-compliance-guide.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-data-privacy-law-vietnam-pdpd-compliance-guide-76a24d43.webp",
    alt: "Data Privacy Law in Vietnam: PDPD Compliance Guide for Bu… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleVietnamConstructionLawPermitsContractsDisputes: {
    id: "article-vietnam-construction-law-permits-contracts-disputes",
    name: "Vietnam Construction Law: Permits, Contracts, and Dispute…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-construction-law-permits-contracts-disputes-fef094d4.webp",
    local: "/images/blog/article-vietnam-construction-law-permits-contracts-disputes.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-construction-law-permits-contracts-disputes-fef094d4.webp",
    alt: "Vietnam Construction Law: Permits, Contracts, and Dispute… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleProtectingTradeSecretsVietnamLegalFramework: {
    id: "article-protecting-trade-secrets-vietnam-legal-framework",
    name: "Protecting Trade Secrets in Vietnam: Legal Framework and …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-protecting-trade-secrets-vietnam-legal-framework-7150cf43.webp",
    local: "/images/blog/article-protecting-trade-secrets-vietnam-legal-framework.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-protecting-trade-secrets-vietnam-legal-framework-7150cf43.webp",
    alt: "Protecting Trade Secrets in Vietnam: Legal Framework and … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleTaxObligationsForeignCompaniesOperatingVietnam: {
    id: "article-tax-obligations-foreign-companies-operating-vietnam",
    name: "Tax Obligations for Foreign Companies Operating in Vietnam",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-tax-obligations-foreign-companies-operating-vietnam-79c9e645.webp",
    local: "/images/blog/article-tax-obligations-foreign-companies-operating-vietnam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-tax-obligations-foreign-companies-operating-vietnam-79c9e645.webp",
    alt: "Tax Obligations for Foreign Companies Operating in Vietnam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleVietnamFranchiseLawForeignFranchisors: {
    id: "article-vietnam-franchise-law-foreign-franchisors",
    name: "Vietnam Franchise Law: Legal Requirements for Foreign Fra…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-franchise-law-foreign-franchisors-24b542fd.webp",
    local: "/images/blog/article-vietnam-franchise-law-foreign-franchisors.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-franchise-law-foreign-franchisors-24b542fd.webp",
    alt: "Vietnam Franchise Law: Legal Requirements for Foreign Fra… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleDisputeResolutionVietnamLitigationArbitrationMediation: {
    id: "article-dispute-resolution-vietnam-litigation-arbitration-mediation",
    name: "Dispute Resolution in Vietnam: Litigation vs Arbitration …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-dispute-resolution-vietnam-litigation-arbitration-mediation-2f0daad2.webp",
    local: "/images/blog/article-dispute-resolution-vietnam-litigation-arbitration-mediation.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-dispute-resolution-vietnam-litigation-arbitration-mediation-2f0daad2.webp",
    alt: "Dispute Resolution in Vietnam: Litigation vs Arbitration … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleUnderstandingVietnamLaborLawGuideForeignEmployers: {
    id: "article-understanding-vietnam-labor-law-guide-foreign-employers",
    name: "Understanding Vietnam Labor Law: A Guide for Foreign Empl…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-understanding-vietnam-labor-law-guide-foreign-employers-88406995.webp",
    local: "/images/blog/article-understanding-vietnam-labor-law-guide-foreign-employers.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-understanding-vietnam-labor-law-guide-foreign-employers-88406995.webp",
    alt: "Understanding Vietnam Labor Law: A Guide for Foreign Empl… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleVietnamRealEstatePurchaseAgreementForeignBuyers: {
    id: "article-vietnam-real-estate-purchase-agreement-foreign-buyers",
    name: "Vietnam Real Estate Purchase Agreement: Essential Clauses…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-real-estate-purchase-agreement-foreign-buyers-b768f167.webp",
    local: "/images/blog/article-vietnam-real-estate-purchase-agreement-foreign-buyers.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-real-estate-purchase-agreement-foreign-buyers-b768f167.webp",
    alt: "Vietnam Real Estate Purchase Agreement: Essential Clauses… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleQuyTrinhGiamDocThamTaiThamToTungDanSu: {
    id: "article-quy-trinh-giam-doc-tham-tai-tham-to-tung-dan-su",
    name: "Quy Trình Giám Đốc Thẩm và Tái Thẩm Trong Tố Tụng Dân Sự",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quy-trinh-giam-doc-tham-tai-tham-to-tung-dan-su-7e0e20d0.webp",
    local: "/images/blog/article-quy-trinh-giam-doc-tham-tai-tham-to-tung-dan-su.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quy-trinh-giam-doc-tham-tai-tham-to-tung-dan-su-7e0e20d0.webp",
    alt: "Quy Trình Giám Đốc Thẩm và Tái Thẩm Trong Tố Tụng Dân Sự - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articlePhapLuatHopDongDienTuTaiVietNam: {
    id: "article-phap-luat-hop-dong-dien-tu-tai-viet-nam",
    name: "Pháp Luật Về Hợp Đồng Điện Tử Tại Việt Nam",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-phap-luat-hop-dong-dien-tu-tai-viet-nam-4e0b1fc1.webp",
    local: "/images/blog/article-phap-luat-hop-dong-dien-tu-tai-viet-nam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-phap-luat-hop-dong-dien-tu-tai-viet-nam-4e0b1fc1.webp",
    alt: "Pháp Luật Về Hợp Đồng Điện Tử Tại Việt Nam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleHuongDanKhieuNaiQuyetDinhHanhChinhDatDai: {
    id: "article-huong-dan-khieu-nai-quyet-dinh-hanh-chinh-dat-dai",
    name: "Hướng Dẫn Khiếu Nại Quyết Định Hành Chính Về Đất Đai",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-huong-dan-khieu-nai-quyet-dinh-hanh-chinh-dat-dai-1d464cc9.webp",
    local: "/images/blog/article-huong-dan-khieu-nai-quyet-dinh-hanh-chinh-dat-dai.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-huong-dan-khieu-nai-quyet-dinh-hanh-chinh-dat-dai-1d464cc9.webp",
    alt: "Hướng Dẫn Khiếu Nại Quyết Định Hành Chính Về Đất Đai - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleGiaiQuyetTranhChapGiuaThanhVienCongTyTnhh: {
    id: "article-giai-quyet-tranh-chap-giua-thanh-vien-cong-ty-tnhh",
    name: "Giải Quyết Tranh Chấp Giữa Thành Viên Công Ty TNHH",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-giai-quyet-tranh-chap-giua-thanh-vien-cong-ty-tnhh-5f1577a5.webp",
    local: "/images/blog/article-giai-quyet-tranh-chap-giua-thanh-vien-cong-ty-tnhh.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-giai-quyet-tranh-chap-giua-thanh-vien-cong-ty-tnhh-5f1577a5.webp",
    alt: "Giải Quyết Tranh Chấp Giữa Thành Viên Công Ty TNHH - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleQuyenSoHuuTriTueThoiDaiSoBaoVeTacPham: {
    id: "article-quyen-so-huu-tri-tue-thoi-dai-so-bao-ve-tac-pham",
    name: "Quyền Sở Hữu Trí Tuệ Trong Thời Đại Số: Bảo Vệ Tác Phẩm O…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-so-huu-tri-tue-thoi-dai-so-bao-ve-tac-pham-eb51a939.webp",
    local: "/images/blog/article-quyen-so-huu-tri-tue-thoi-dai-so-bao-ve-tac-pham.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-so-huu-tri-tue-thoi-dai-so-bao-ve-tac-pham-eb51a939.webp",
    alt: "Quyền Sở Hữu Trí Tuệ Trong Thời Đại Số: Bảo Vệ Tác Phẩm O… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleBoiThuongTaiNanGiaoThongQuyDinhThucTien: {
    id: "article-boi-thuong-tai-nan-giao-thong-quy-dinh-thuc-tien",
    name: "Bồi Thường Khi Bị Tai Nạn Giao Thông: Quy Định và Thực Tiễn",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-boi-thuong-tai-nan-giao-thong-quy-dinh-thuc-tien-1f1e7df9.webp",
    local: "/images/blog/article-boi-thuong-tai-nan-giao-thong-quy-dinh-thuc-tien.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-boi-thuong-tai-nan-giao-thong-quy-dinh-thuc-tien-1f1e7df9.webp",
    alt: "Bồi Thường Khi Bị Tai Nạn Giao Thông: Quy Định và Thực Tiễn - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articlePhapLuatChoVayNgangHangP2pLendingVietNam: {
    id: "article-phap-luat-cho-vay-ngang-hang-p2p-lending-viet-nam",
    name: "Pháp Luật Về Cho Vay Ngang Hàng (P2P Lending) Tại Việt Nam",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-phap-luat-cho-vay-ngang-hang-p2p-lending-viet-nam-75cc144d.webp",
    local: "/images/blog/article-phap-luat-cho-vay-ngang-hang-p2p-lending-viet-nam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-phap-luat-cho-vay-ngang-hang-p2p-lending-viet-nam-75cc144d.webp",
    alt: "Pháp Luật Về Cho Vay Ngang Hàng (P2P Lending) Tại Việt Nam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleQuyTrinhThiHanhAnDanSuTuBanAnDenThucThi: {
    id: "article-quy-trinh-thi-hanh-an-dan-su-tu-ban-an-den-thuc-thi",
    name: "Quy Trình Thi Hành Án Dân Sự: Từ Bản Án Đến Thực Thi",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quy-trinh-thi-hanh-an-dan-su-tu-ban-an-den-thuc-thi-48afd2d7.webp",
    local: "/images/blog/article-quy-trinh-thi-hanh-an-dan-su-tu-ban-an-den-thuc-thi.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quy-trinh-thi-hanh-an-dan-su-tu-ban-an-den-thuc-thi-48afd2d7.webp",
    alt: "Quy Trình Thi Hành Án Dân Sự: Từ Bản Án Đến Thực Thi - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLuatNhaO2023ThayDoiAnhHuongNguoiMuaNha: {
    id: "article-luat-nha-o-2023-thay-doi-anh-huong-nguoi-mua-nha",
    name: "Luật Nhà Ở 2023: Những Thay Đổi Ảnh Hưởng Đến Người Mua Nhà",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-luat-nha-o-2023-thay-doi-anh-huong-nguoi-mua-nha-d96519b6.webp",
    local: "/images/blog/article-luat-nha-o-2023-thay-doi-anh-huong-nguoi-mua-nha.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-luat-nha-o-2023-thay-doi-anh-huong-nguoi-mua-nha-d96519b6.webp",
    alt: "Luật Nhà Ở 2023: Những Thay Đổi Ảnh Hưởng Đến Người Mua Nhà - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleGiaiQuyetTranhChapBangHoaGiai: {
    id: "article-giai-quyet-tranh-chap-bang-hoa-giai",
    name: "Giải Quyết Tranh Chấp Bằng Hòa Giải: Phương Thức Thay Thế…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-giai-quyet-tranh-chap-bang-hoa-giai-8cf842a3.webp",
    local: "/images/blog/article-giai-quyet-tranh-chap-bang-hoa-giai.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-giai-quyet-tranh-chap-bang-hoa-giai-8cf842a3.webp",
    alt: "Giải Quyết Tranh Chấp Bằng Hòa Giải: Phương Thức Thay Thế… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleThuTucXinCapPhepXayDungHuongDan: {
    id: "article-thu-tuc-xin-cap-phep-xay-dung-huong-dan",
    name: "Thủ Tục Xin Cấp Phép Xây Dựng: Hướng Dẫn Chi Tiết",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-thu-tuc-xin-cap-phep-xay-dung-huong-dan-4c2c170a.webp",
    local: "/images/blog/article-thu-tuc-xin-cap-phep-xay-dung-huong-dan.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-thu-tuc-xin-cap-phep-xay-dung-huong-dan-4c2c170a.webp",
    alt: "Thủ Tục Xin Cấp Phép Xây Dựng: Hướng Dẫn Chi Tiết - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleToiPhamCongNgheCaoThucTrangPhongChong: {
    id: "article-toi-pham-cong-nghe-cao-thuc-trang-phong-chong",
    name: "Tội Phạm Công Nghệ Cao: Thực Trạng và Phòng Chống",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-toi-pham-cong-nghe-cao-thuc-trang-phong-chong-f73da41e.webp",
    local: "/images/blog/article-toi-pham-cong-nghe-cao-thuc-trang-phong-chong.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-toi-pham-cong-nghe-cao-thuc-trang-phong-chong-f73da41e.webp",
    alt: "Tội Phạm Công Nghệ Cao: Thực Trạng và Phòng Chống - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleTranhChapHopDongThueNhaQuyenNghiaVu: {
    id: "article-tranh-chap-hop-dong-thue-nha-quyen-nghia-vu",
    name: "Tranh Chấp Hợp Đồng Thuê Nhà: Quyền Và Nghĩa Vụ Của Các Bên",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-tranh-chap-hop-dong-thue-nha-quyen-nghia-vu-f15a7ec2.webp",
    local: "/images/blog/article-tranh-chap-hop-dong-thue-nha-quyen-nghia-vu.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-tranh-chap-hop-dong-thue-nha-quyen-nghia-vu-f15a7ec2.webp",
    alt: "Tranh Chấp Hợp Đồng Thuê Nhà: Quyền Và Nghĩa Vụ Của Các Bên - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleBaoHiemXaHoiMotLanDieuKienThuTuc: {
    id: "article-bao-hiem-xa-hoi-mot-lan-dieu-kien-thu-tuc",
    name: "Bảo Hiểm Xã Hội Một Lần: Điều Kiện, Thủ Tục và Lưu Ý",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-bao-hiem-xa-hoi-mot-lan-dieu-kien-thu-tuc-6bc9dbce.webp",
    local: "/images/blog/article-bao-hiem-xa-hoi-mot-lan-dieu-kien-thu-tuc.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-bao-hiem-xa-hoi-mot-lan-dieu-kien-thu-tuc-6bc9dbce.webp",
    alt: "Bảo Hiểm Xã Hội Một Lần: Điều Kiện, Thủ Tục và Lưu Ý - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleHopDongDatCocMuaBatDongSanRuiRo: {
    id: "article-hop-dong-dat-coc-mua-bat-dong-san-rui-ro",
    name: "Hợp Đồng Đặt Cọc Mua Bất Động Sản: Rủi Ro và Cách Phòng T…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-hop-dong-dat-coc-mua-bat-dong-san-rui-ro-09ac0993.webp",
    local: "/images/blog/article-hop-dong-dat-coc-mua-bat-dong-san-rui-ro.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-hop-dong-dat-coc-mua-bat-dong-san-rui-ro-09ac0993.webp",
    alt: "Hợp Đồng Đặt Cọc Mua Bất Động Sản: Rủi Ro và Cách Phòng T… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articlePhaSanDoanhNghiepQuyTrinhPhapLyHeQua: {
    id: "article-pha-san-doanh-nghiep-quy-trinh-phap-ly-he-qua",
    name: "Phá Sản Doanh Nghiệp: Quy Trình Pháp Lý Và Hệ Quả",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-pha-san-doanh-nghiep-quy-trinh-phap-ly-he-qua-d4893d82.webp",
    local: "/images/blog/article-pha-san-doanh-nghiep-quy-trinh-phap-ly-he-qua.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-pha-san-doanh-nghiep-quy-trinh-phap-ly-he-qua-d4893d82.webp",
    alt: "Phá Sản Doanh Nghiệp: Quy Trình Pháp Lý Và Hệ Quả - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleBaoHoNhanHieuTaiVietNamDangKyBaoVe: {
    id: "article-bao-ho-nhan-hieu-tai-viet-nam-dang-ky-bao-ve",
    name: "Bảo Hộ Nhãn Hiệu Tại Việt Nam: Từ Đăng Ký Đến Bảo Vệ Quyền",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-bao-ho-nhan-hieu-tai-viet-nam-dang-ky-bao-ve-5a1e56c5.webp",
    local: "/images/blog/article-bao-ho-nhan-hieu-tai-viet-nam-dang-ky-bao-ve.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-bao-ho-nhan-hieu-tai-viet-nam-dang-ky-bao-ve-5a1e56c5.webp",
    alt: "Bảo Hộ Nhãn Hiệu Tại Việt Nam: Từ Đăng Ký Đến Bảo Vệ Quyền - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleThuTucDangKyKetHonVoiNguoiNuocNgoai: {
    id: "article-thu-tuc-dang-ky-ket-hon-voi-nguoi-nuoc-ngoai",
    name: "Thủ Tục Đăng Ký Kết Hôn Với Người Nước Ngoài Tại Việt Nam",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-thu-tuc-dang-ky-ket-hon-voi-nguoi-nuoc-ngoai-069b8f21.webp",
    local: "/images/blog/article-thu-tuc-dang-ky-ket-hon-voi-nguoi-nuoc-ngoai.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-thu-tuc-dang-ky-ket-hon-voi-nguoi-nuoc-ngoai-069b8f21.webp",
    alt: "Thủ Tục Đăng Ký Kết Hôn Với Người Nước Ngoài Tại Việt Nam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleTrongTaiThuongMaiVietNamUuDiemQuyTrinh: {
    id: "article-trong-tai-thuong-mai-viet-nam-uu-diem-quy-trinh",
    name: "Trọng Tài Thương Mại Tại Việt Nam: Ưu Điểm Và Quy Trình",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-trong-tai-thuong-mai-viet-nam-uu-diem-quy-trinh-d14840b2.webp",
    local: "/images/blog/article-trong-tai-thuong-mai-viet-nam-uu-diem-quy-trinh.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-trong-tai-thuong-mai-viet-nam-uu-diem-quy-trinh-d14840b2.webp",
    alt: "Trọng Tài Thương Mại Tại Việt Nam: Ưu Điểm Và Quy Trình - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLuatLaoDong2019QuyenLoiMoiNguoiLaoDong: {
    id: "article-luat-lao-dong-2019-quyen-loi-moi-nguoi-lao-dong",
    name: "Luật Lao Động 2019: Quyền Lợi Mới Của Người Lao Động",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-luat-lao-dong-2019-quyen-loi-moi-nguoi-lao-dong-47fa4cbe.webp",
    local: "/images/blog/article-luat-lao-dong-2019-quyen-loi-moi-nguoi-lao-dong.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-luat-lao-dong-2019-quyen-loi-moi-nguoi-lao-dong-47fa4cbe.webp",
    alt: "Luật Lao Động 2019: Quyền Lợi Mới Của Người Lao Động - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleGiaiQuyetTranhChapThuaKeTaiSan: {
    id: "article-giai-quyet-tranh-chap-thua-ke-tai-san",
    name: "Giải Quyết Tranh Chấp Thừa Kế Tài Sản: Quy Trình và Kinh …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-giai-quyet-tranh-chap-thua-ke-tai-san-35989cea.webp",
    local: "/images/blog/article-giai-quyet-tranh-chap-thua-ke-tai-san.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-giai-quyet-tranh-chap-thua-ke-tai-san-35989cea.webp",
    alt: "Giải Quyết Tranh Chấp Thừa Kế Tài Sản: Quy Trình và Kinh … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleQuyenNguoiTieuDungPhapLuatVietNam: {
    id: "article-quyen-nguoi-tieu-dung-phap-luat-viet-nam",
    name: "Quyền Của Người Tiêu Dùng Theo Pháp Luật Việt Nam: Bảo Vệ…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-nguoi-tieu-dung-phap-luat-viet-nam-f99381c5.webp",
    local: "/images/blog/article-quyen-nguoi-tieu-dung-phap-luat-viet-nam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-nguoi-tieu-dung-phap-luat-viet-nam-f99381c5.webp",
    alt: "Quyền Của Người Tiêu Dùng Theo Pháp Luật Việt Nam: Bảo Vệ… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleThanhLapCongTyVonDauTuNuocNgoaiVietNam: {
    id: "article-thanh-lap-cong-ty-von-dau-tu-nuoc-ngoai-viet-nam",
    name: "Thành Lập Công Ty Có Vốn Đầu Tư Nước Ngoài Tại Việt Nam: …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-thanh-lap-cong-ty-von-dau-tu-nuoc-ngoai-viet-nam-2ae4c69c.webp",
    local: "/images/blog/article-thanh-lap-cong-ty-von-dau-tu-nuoc-ngoai-viet-nam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-thanh-lap-cong-ty-von-dau-tu-nuoc-ngoai-viet-nam-2ae4c69c.webp",
    alt: "Thành Lập Công Ty Có Vốn Đầu Tư Nước Ngoài Tại Việt Nam: … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleHopDongMuaBanNhaDatDieuKhoanQuanTrong: {
    id: "article-hop-dong-mua-ban-nha-dat-dieu-khoan-quan-trong",
    name: "Hợp Đồng Mua Bán Nhà Đất: Những Điều Khoản Quan Trọng Cần…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-hop-dong-mua-ban-nha-dat-dieu-khoan-quan-trong-f0371fe6.webp",
    local: "/images/blog/article-hop-dong-mua-ban-nha-dat-dieu-khoan-quan-trong.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-hop-dong-mua-ban-nha-dat-dieu-khoan-quan-trong-f0371fe6.webp",
    alt: "Hợp Đồng Mua Bán Nhà Đất: Những Điều Khoản Quan Trọng Cần… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleHowToChooseLawyerVietnamGuideInternationalClients: {
    id: "article-how-to-choose-lawyer-vietnam-guide-international-clients",
    name: "How to Choose a Lawyer in Vietnam: A Practical Guide for …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-how-to-choose-lawyer-vietnam-guide-international-clients-bc257a9c.webp",
    local: "/images/blog/article-how-to-choose-lawyer-vietnam-guide-international-clients.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-how-to-choose-lawyer-vietnam-guide-international-clients-bc257a9c.webp",
    alt: "How to Choose a Lawyer in Vietnam: A Practical Guide for … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleCriminalLawVietnamWhatForeignNationalsNeedToKnow: {
    id: "article-criminal-law-vietnam-what-foreign-nationals-need-to-know",
    name: "Criminal Law in Vietnam: What Foreign Nationals Need to Know",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-criminal-law-vietnam-what-foreign-nationals-need-to-know-5df0a411.webp",
    local: "/images/blog/article-criminal-law-vietnam-what-foreign-nationals-need-to-know.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-criminal-law-vietnam-what-foreign-nationals-need-to-know-5df0a411.webp",
    alt: "Criminal Law in Vietnam: What Foreign Nationals Need to Know - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleHowToEnforceForeignCourtJudgmentInVietnam: {
    id: "article-how-to-enforce-foreign-court-judgment-in-vietnam",
    name: "How to Enforce a Foreign Court Judgment in Vietnam",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-how-to-enforce-foreign-court-judgment-in-vietnam-04561ca5.webp",
    local: "/images/blog/article-how-to-enforce-foreign-court-judgment-in-vietnam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-how-to-enforce-foreign-court-judgment-in-vietnam-04561ca5.webp",
    alt: "How to Enforce a Foreign Court Judgment in Vietnam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleResolvingCommercialDisputesVietnamLitigationVsArbitration: {
    id: "article-resolving-commercial-disputes-vietnam-litigation-vs-arbitration",
    name: "Resolving Commercial Disputes in Vietnam: Litigation vs A…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-resolving-commercial-disputes-vietnam-litigation-vs-arbitration-5844c682.webp",
    local: "/images/blog/article-resolving-commercial-disputes-vietnam-litigation-vs-arbitration.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-resolving-commercial-disputes-vietnam-litigation-vs-arbitration-5844c682.webp",
    alt: "Resolving Commercial Disputes in Vietnam: Litigation vs A… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleEmploymentLawVietnamGuideForeignEmployersEmployees: {
    id: "article-employment-law-vietnam-guide-foreign-employers-employees",
    name: "Employment Law in Vietnam: A Guide for Foreign Employers …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-employment-law-vietnam-guide-foreign-employers-employees-b3b01a7a.webp",
    local: "/images/blog/article-employment-law-vietnam-guide-foreign-employers-employees.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-employment-law-vietnam-guide-foreign-employers-employees-b3b01a7a.webp",
    alt: "Employment Law in Vietnam: A Guide for Foreign Employers … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleBuyingPropertyVietnamForeignerLegalRightsRestrictionsProcess: {
    id: "article-buying-property-vietnam-foreigner-legal-rights-restrictions-process",
    name: "Buying Property in Vietnam as a Foreigner: Legal Rights, …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-buying-property-vietnam-foreigner-legal-rights-restrictions-process-8ef0659c.webp",
    local: "/images/blog/article-buying-property-vietnam-foreigner-legal-rights-restrictions-process.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-buying-property-vietnam-foreigner-legal-rights-restrictions-process-8ef0659c.webp",
    alt: "Buying Property in Vietnam as a Foreigner: Legal Rights, … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleGettingDivorcedVietnamForeignerGuide: {
    id: "article-getting-divorced-vietnam-foreigner-guide",
    name: "Getting Divorced in Vietnam as a Foreigner: Everything Yo…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-getting-divorced-vietnam-foreigner-guide-65233ddf.webp",
    local: "/images/blog/article-getting-divorced-vietnam-foreigner-guide.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-getting-divorced-vietnam-foreigner-guide-65233ddf.webp",
    alt: "Getting Divorced in Vietnam as a Foreigner: Everything Yo… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleProtectingIntellectualPropertyVietnamPracticalLegalGuide: {
    id: "article-protecting-intellectual-property-vietnam-practical-legal-guide",
    name: "Protecting Intellectual Property in Vietnam: A Practical …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-protecting-intellectual-property-vietnam-practical-legal-guide-65631216.webp",
    local: "/images/blog/article-protecting-intellectual-property-vietnam-practical-legal-guide.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-protecting-intellectual-property-vietnam-practical-legal-guide-65631216.webp",
    alt: "Protecting Intellectual Property in Vietnam: A Practical … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleVietnamMaGuideLegalFrameworkDueDiligenceDealStructures: {
    id: "article-vietnam-ma-guide-legal-framework-due-diligence-deal-structures",
    name: "Vietnam M&A Guide: Legal Framework, Due Diligence and Dea…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-ma-guide-legal-framework-due-diligence-deal-structures-860570be.webp",
    local: "/images/blog/article-vietnam-ma-guide-legal-framework-due-diligence-deal-structures.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-vietnam-ma-guide-legal-framework-due-diligence-deal-structures-860570be.webp",
    alt: "Vietnam M&A Guide: Legal Framework, Due Diligence and Dea… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleSettingUpBusinessVietnamForeignInvestorsGuide2026: {
    id: "article-setting-up-business-vietnam-foreign-investors-guide-2026",
    name: "Setting Up a Business in Vietnam: Complete Legal Guide fo…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-setting-up-business-vietnam-foreign-investors-guide-2026-d1bf84f8.webp",
    local: "/images/blog/article-setting-up-business-vietnam-foreign-investors-guide-2026.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-setting-up-business-vietnam-foreign-investors-guide-2026-d1bf84f8.webp",
    alt: "Setting Up a Business in Vietnam: Complete Legal Guide fo… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleKhiNaoBanCanThueLuatSu10TinhHuongPhoBienNhat: {
    id: "article-khi-nao-ban-can-thue-luat-su-10-tinh-huong-pho-bien-nhat",
    name: "Khi Nào Bạn Cần Thuê Luật Sư? 10 Tình Huống Phổ Biến Nhất",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-khi-nao-ban-can-thue-luat-su-10-tinh-huong-pho-bien-nhat-0720f199.webp",
    local: "/images/blog/article-khi-nao-ban-can-thue-luat-su-10-tinh-huong-pho-bien-nhat.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-khi-nao-ban-can-thue-luat-su-10-tinh-huong-pho-bien-nhat-0720f199.webp",
    alt: "Khi Nào Bạn Cần Thuê Luật Sư? 10 Tình Huống Phổ Biến Nhất - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleQuyenCuaBiCanBiCaoTrongToTungHinhSuVietNam: {
    id: "article-quyen-cua-bi-can-bi-cao-trong-to-tung-hinh-su-viet-nam",
    name: "Quyền Của Bị Can Bị Cáo Trong Tố Tụng Hình Sự Việt Nam",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-cua-bi-can-bi-cao-trong-to-tung-hinh-su-viet-nam-ca002c3e.webp",
    local: "/images/blog/article-quyen-cua-bi-can-bi-cao-trong-to-tung-hinh-su-viet-nam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-cua-bi-can-bi-cao-trong-to-tung-hinh-su-viet-nam-ca002c3e.webp",
    alt: "Quyền Của Bị Can Bị Cáo Trong Tố Tụng Hình Sự Việt Nam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleSaThaiTraiPhapLuatQuyenNguoiLaoDongVaCachKhieuNai: {
    id: "article-sa-thai-trai-phap-luat-quyen-nguoi-lao-dong-va-cach-khieu-nai",
    name: "Sa Thải Trái Pháp Luật: Quyền Của Người Lao Động Và Cách …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-sa-thai-trai-phap-luat-quyen-nguoi-lao-dong-va-cach-khieu-nai-8317837f.webp",
    local: "/images/blog/article-sa-thai-trai-phap-luat-quyen-nguoi-lao-dong-va-cach-khieu-nai.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-sa-thai-trai-phap-luat-quyen-nguoi-lao-dong-va-cach-khieu-nai-8317837f.webp",
    alt: "Sa Thải Trái Pháp Luật: Quyền Của Người Lao Động Và Cách … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleMuaBanSapNhapDoanhNghiepMaTaiVietNamQuyTrinhPhapLy: {
    id: "article-mua-ban-sap-nhap-doanh-nghiep-ma-tai-viet-nam-quy-trinh-phap-ly",
    name: "Mua Bán Sáp Nhập Doanh Nghiệp (M&A) Tại Việt Nam: Quy Trì…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-mua-ban-sap-nhap-doanh-nghiep-ma-tai-viet-nam-quy-trinh-phap-ly-9ec42304.webp",
    local: "/images/blog/article-mua-ban-sap-nhap-doanh-nghiep-ma-tai-viet-nam-quy-trinh-phap-ly.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-mua-ban-sap-nhap-doanh-nghiep-ma-tai-viet-nam-quy-trinh-phap-ly-9ec42304.webp",
    alt: "Mua Bán Sáp Nhập Doanh Nghiệp (M&A) Tại Việt Nam: Quy Trì… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleQuyenNuoiConSauLyHonPhapLuatVaThucTienXetXu: {
    id: "article-quyen-nuoi-con-sau-ly-hon-phap-luat-va-thuc-tien-xet-xu",
    name: "Quyền Nuôi Con Sau Ly Hôn: Pháp Luật Và Thực Tiễn Xét Xử",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-nuoi-con-sau-ly-hon-phap-luat-va-thuc-tien-xet-xu-7ac08b6e.webp",
    local: "/images/blog/article-quyen-nuoi-con-sau-ly-hon-phap-luat-va-thuc-tien-xet-xu.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quyen-nuoi-con-sau-ly-hon-phap-luat-va-thuc-tien-xet-xu-7ac08b6e.webp",
    alt: "Quyền Nuôi Con Sau Ly Hôn: Pháp Luật Và Thực Tiễn Xét Xử - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLyHonCoYeuToNuocNgoaiTaiVietNamHuongDanToanDien: {
    id: "article-ly-hon-co-yeu-to-nuoc-ngoai-tai-viet-nam-huong-dan-toan-dien",
    name: "Ly Hôn Có Yếu Tố Nước Ngoài Tại Việt Nam: Hướng Dẫn Toàn …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-ly-hon-co-yeu-to-nuoc-ngoai-tai-viet-nam-huong-dan-toan-dien-3fc2df20.webp",
    local: "/images/blog/article-ly-hon-co-yeu-to-nuoc-ngoai-tai-viet-nam-huong-dan-toan-dien.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-ly-hon-co-yeu-to-nuoc-ngoai-tai-viet-nam-huong-dan-toan-dien-3fc2df20.webp",
    alt: "Ly Hôn Có Yếu Tố Nước Ngoài Tại Việt Nam: Hướng Dẫn Toàn … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleTranhChapDatDaiTaiTphcmNguyenNhanGiaiPhapKinhNghiem: {
    id: "article-tranh-chap-dat-dai-tai-tphcm-nguyen-nhan-giai-phap-kinh-nghiem",
    name: "Tranh Chấp Đất Đai Tại TP.HCM: Nguyên Nhân, Giải Pháp Và …",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-tranh-chap-dat-dai-tai-tphcm-nguyen-nhan-giai-phap-kinh-nghiem-040ee398.webp",
    local: "/images/blog/article-tranh-chap-dat-dai-tai-tphcm-nguyen-nhan-giai-phap-kinh-nghiem.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-tranh-chap-dat-dai-tai-tphcm-nguyen-nhan-giai-phap-kinh-nghiem-040ee398.webp",
    alt: "Tranh Chấp Đất Đai Tại TP.HCM: Nguyên Nhân, Giải Pháp Và … - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleLuatDatDai2024NhungThayDoiQuanTrongNhat: {
    id: "article-luat-dat-dai-2024-nhung-thay-doi-quan-trong-nhat",
    name: "Luật Đất Đai 2024: Những Thay Đổi Quan Trọng Nhất Ảnh Hưở…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-luat-dat-dai-2024-nhung-thay-doi-quan-trong-nhat-a0a34423.webp",
    local: "/images/blog/article-luat-dat-dai-2024-nhung-thay-doi-quan-trong-nhat.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-luat-dat-dai-2024-nhung-thay-doi-quan-trong-nhat-a0a34423.webp",
    alt: "Luật Đất Đai 2024: Những Thay Đổi Quan Trọng Nhất Ảnh Hưở… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleBoiThuongThietHaiNgoaiHopDongQuyenLoiVaCachBaoVe: {
    id: "article-boi-thuong-thiet-hai-ngoai-hop-dong-quyen-loi-va-cach-bao-ve",
    name: "Bồi Thường Thiệt Hại Ngoài Hợp Đồng: Quyền Lợi Và Cách Bả…",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-boi-thuong-thiet-hai-ngoai-hop-dong-quyen-loi-va-cach-bao-ve-180f28e6.webp",
    local: "/images/blog/article-boi-thuong-thiet-hai-ngoai-hop-dong-quyen-loi-va-cach-bao-ve.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-boi-thuong-thiet-hai-ngoai-hop-dong-quyen-loi-va-cach-bao-ve-180f28e6.webp",
    alt: "Bồi Thường Thiệt Hại Ngoài Hợp Đồng: Quyền Lợi Và Cách Bả… - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  },
  articleQuyTrinhGiaiQuyetTranhChapHopDongTaiToaAnVietNam: {
    id: "article-quy-trinh-giai-quyet-tranh-chap-hop-dong-tai-toa-an-viet-nam",
    name: "Quy Trình Giải Quyết Tranh Chấp Hợp Đồng Tại Tòa Án Việt Nam",
    category: "blog",
    cdn: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quy-trinh-giai-quyet-tranh-chap-hop-dong-tai-toa-an-viet-nam-25113ccc.webp",
    local: "/images/blog/article-quy-trinh-giai-quyet-tranh-chap-hop-dong-tai-toa-an-viet-nam.webp",
    src: "https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/vothienhien.com/blog/article-quy-trinh-giai-quyet-tranh-chap-hop-dong-tai-toa-an-viet-nam-25113ccc.webp",
    alt: "Quy Trình Giải Quyết Tranh Chấp Hợp Đồng Tại Tòa Án Việt Nam - vothienhien.com",
    width: 1200,
    aspect: "16:9",
  }
} as const;

export type ImageId = keyof typeof IMAGES;
